// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdzmeosyxellwlwxzgme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kem1lb3N5eGVsbHdsd3h6Z21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzAzNjMsImV4cCI6MjA3MjUwNjM2M30.Ymv-WtbK0T0O-JaBgbUpO_iePdiMgEqYv-GwBJZ6bA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});